### ISSUE TITLE
Example of passing MF_SERVICES and MF_ENV via params loaded via fly

### ISSUE THREAD

**Issue by xyloman** [Pivotal-Field-Engineering/pipeline-tasks#3]
We have been working with @phopper-pivotal to implement concourse pipelines for our spring boot applications.  Internally on our team we had implemented a similar project to this project and feel that there is more capabilities that have been implemented that we had yet to implement in our one off implementation.  So after that unnecessary introduction the problem that we are looking to solve is to create a pipeline.yml template that can be reused for many spring boot microservices.  In order to accomplish said template we were wanting to dynamic generic the manifest based upon the params loaded via fly.  All strings work as expected but map and seq params are not working as I would expect.  Here is the example that works:

```
  - task: generate-manifest
    file: pipeline-tasks/generate-manifest/task.yml
    params:
      MF_NAME: {{cf-dev-app-name}}
      MF_HOST: {{cf-dev-app-host}}
      MF_BUILDPACK: {{cf-dev-app-buildpack}}
      MF_SERVICES:
      - mysql
      - rabbitmq
      - registry
      - apm
      - config-server
      - smtp
      - oauth
      - metrics
      - circuit-breaker 
      MF_ENV:
        JAVA_OPTS: -Djava.security.egd=file:/dev/./urandom
        SPRING_PROFILES_ACTIVE: dev,cloud
        JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '[enabled: false]'
``` 

Here is the example that is having issues:

```
  - task: generate-manifest
    file: pipeline-tasks/generate-manifest/task.yml
    params:
      MF_NAME: {{cf-dev-app-name}}
      MF_HOST: {{cf-dev-app-host}}
      MF_BUILDPACK: {{cf-dev-app-buildpack}}
      MF_SERVICES: {{cf-dev-app-services}}
      MF_ENV: {{cf-dev-app-env}}
```

And the params.yml that I was attempting was:

```
cf-dev-app-env: 
  SPRING_PROFILES_ACTIVE: dev,cloud
  JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '[enabled: false]'
  JAVA_OPTS: -Djava.security.egd=file:/dev/./urandom
cf-dev-app-services: 
- mysql
- rabbitmq
- registry
- apm
- config-server
- smtp
- oauth
- metrics
- circuit-breaker
```

Which results in an example when attempting to load the params via fly:

```
cannot unmarshal !!map into string
````

Therefore, some suggestions could be helpful in accomplish this knowing that this might be a limitation on flys ability to merge non string params into the pipeline.

**Comment by xyloman** [comment]
Did some more troubleshooting and we found a possible solution.  When we changed our pipeline.yml from use curly braces to parentheses in all cases the passing of the object now works.  Per my example above we changed the generate manifest task to the following:

```
- task: generate-manifest
    file: pipeline-tasks/generate-manifest/task.yml
    params:
      MF_NAME: ((cf-dev-app-name))
      MF_HOST: ((cf-dev-app-host))
      MF_BUILDPACK: ((cf-dev-app-buildpack))
      MF_SERVICES: ((cf-dev-app-services))
      MF_ENV: ((cf-dev-app-env))
```

Which gave us the ability to pass around the services and env param object instead of forcing them to be translated to string.  One interesting note is on our concourse 3.5.0 server we had to change all param references in the pipeline.yml from using {{ to use (( in order to avoid the cannot marshal error that we saw from fly.   This has also allowed the ability to pass all of the params as one var in the param file such as the following
```
  - task: generate-manifest
    file: pipeline-tasks/generate-manifest/task.yml
    params: ((cf-dev-app-manifest-params))
```

This allows for the highest possible reuse of the pipeline between projects.
